### PR TITLE
Fix glitch epoch

### PR DESCRIPTION
**Pull request by luojing1211**
I think this fixes the glitch issue.  Places I changed:
1. Change the numerical step size
2. Avoid fitting GLEP and GLPH together.

### CODE REVIEW

**Comment by scottransom** [comment]
I can't merge this now as there are conflicts and 40+ differing files!  Can you make a new PR against my glitchfix branch?  If so, I'll merge that and then make a new PR.

**Comment by luojing1211** [comment]
Let do this in the Nanograv branch. You merge your change to the master, and I will make a new PR based on the new master.

**Comment by scottransom** [comment]
I don't think that makes sense.  There are 40+ files worth of (incorrect) changes here.  My master branch and glitchfix branches are both up-to-date with the NANOGrav master.  If you will just provide the diffs of your fixes to that, I can merge them into my glitchfix branch and simply make a new PR that references this one.

**Comment by scottransom** [comment]
I think that what happened was that your PR to my glitchfix branch (which had all of the recent changes to NANOGrav master) was automatically merged into this PR since you have admin rights here.

**Comment by luojing1211** [comment]
Ok, let me do it again.

**Pull request closed without merging**
